# Generated by Django 5.2.5 on 2025-08-15 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_userevent_inscrit'),
    ]

    operations = [
        migrations.AddField(
            model_name='userevent',
            name='bike',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='userevent',
            name='goal',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
