# Generated by Django 5.2.5 on 2025-08-15 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_userevent_bike_userevent_goal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userevent',
            name='bike',
        ),
        migrations.RemoveField(
            model_name='userevent',
            name='goal',
        ),
        migrations.AddField(
            model_name='inscrit',
            name='bike',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='inscrit',
            name='goal',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
