# Generated by Django 5.2.5 on 2025-08-16 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_remove_userevent_bike_remove_userevent_goal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='subscribe_places',
            field=models.IntegerField(),
        ),
    ]
